name = "qa-system"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 存放验证问题
[[kv_namespaces]]
binding = "KV"
id = "$KV_ID"
preview_id = "$KV_PREVIEW_ID"

# 存放会话数据 + 登录限流计数
[[kv_namespaces]]
binding = "SESSION_STORE"
id = "$SESSION_STORE_ID"
preview_id = "$SESSION_STORE_PREVIEW_ID"
